version: '2.22'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: product-micro
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
